<<<<<<< HEAD
version: "3.9"
services:
 api:
   build: .
   image: ipme/education
   links:
     - "ipme_mysql_57:db"
   ports:
     - "5020:8080"
 db:
   image: mysql:5.7
   environment:
     - MYSQL_ROOT_PASSWORD=root

 ipme_phpmyadmin:
     image: phpmyadmin
     ports:
       - "5010:80"
     links:
       - "ipme_mysql_57:db"
=======
/*modele du prof*/
version: "3.9"
services:
  api:
    build: .
    links:
      - "db:projectdb"
    environment:
      - IPME_DB_HOST=projectdb
    ports:
      - "6011:8080"
  db:
    image: mysql:5.7
    restart: unless-stoppe
    environment:
      - MYSQL_ROOT_PASSWORD=nose123
      - MSQL_DATABASE=ipme
    healthcheck:

  phpmyadmin:
    image: phpmyadmin:5.1.3-apache
    restart: unless-stopped
    environment:
      - PMA_USER=root
      - PMA_HOST=ipmedb
      - PMA_PASSWORD=ipme
    port:
      - "6010:80"
    links:
      -"db:ipmedb"
>>>>>>> 103f792 (config et compose)
