version: "3.9"
services:
 api:
   build: .
   image: ipme/education
   links:
     - "ipme_mysql_57:db"
   ports:
     - "5020:8080"
 db:
   image: mysql:5.7
   environment:
     - MYSQL_ROOT_PASSWORD=root

 ipme_phpmyadmin:
     image: phpmyadmin
     ports:
       - "5010:80"
     links:
       - "ipme_mysql_57:db"